#!/usr/bin/env python3
"""Regenerate file_list.txt for a Litto3D product (NOT part of the build).

The build itself just fetches the URLs in file_list.txt. Re-run this only when Shom
republishes the product (a new prépaquet grid) or a new Litto3D zone is ingested:

  python harvest.py            # lists the prépaquets of GROUP, rewrites file_list.txt

Shom serves Litto3D through an INSPIRE pre-packaged download service — three
unauthenticated HTTPS calls, no account, no cart (the diffusion.shom.fr "Ajouter au
panier" button is a second, login-gated front end over the same archives):

  groups:    GET {BASE}?request=GetCapabilities        → every <Name> pack group
  packages:  GET {BASE}/{group}                        → prepackageResources[].prepackageName
  files:     GET {BASE}/{group}/prepackage/{name}      → downloadFiles[] {fileName,fileSize,fileMd5}
  download:  GET {BASE}/{group}/prepackage/{name}/file/{fileName}   → application/x-7z-compressed

One prépaquet is a ~7.5 km square holding the 1 km² dalles under it, each with MNT1m/
and MNT5m/ ESRI ASCII grids, the ground point cloud, and the distance/source masks.
The point cloud is ~95% of the bytes and the build reads none of it — 191 GB of
downloads yield ~1 GB of 5 m grids. The archives are staged and discarded (raws are
temp()), so that 191 GB is transient volume, never a resident cost.

The other zones are the same service under a different group (sizes are download bytes):

  LITTO3D_NAQ_2020_2022_PACK_DL   219 GB   L3D_MAR_NHDF_2016_2018_PACK_DL   369 GB
  L3D_MAR_CORSE_2017_2018_PACK_DL 299 GB   LITTO3D_FINISTR_2014_PACK_DL      30 GB
  LITTO3D_PACA_2015_PACK_DL        23 GB   L3D_MAR_LR_2014_2015_PACK_DL      56 GB
  LITTO3D_LR_2009_PACK_DL          12 GB   L3D_LIDAR_RANCE_2019_PACK_DL      26 GB
  LITTO3D_GUAD_2016_PACK_DL        10 GB   LITTO3D_MART_2016_PACK_DL          7 GB
  LITTO3D_REUNION_2016_PACK_DL     14 GB   LITTO3D_MAYOT_2012_PACK_DL         5 GB
  LITTO3D_STMARTIN_2019_PACK_DL    33 GB   LITTO3D_STBARTHELEMY_2019_PACK_DL 13 GB
  LITTO3D_SPM_2023_PACK_DL        269 GB   LITTO3D_EPARSES_2012_PACK_DL       2 GB

Each ships its own horizontal frame and its own legal altitude system, so each is its
own source directory rather than a member glob here. SPM splits its archives into
multi-volume 7z parts (.7z.001/.002/.003), which the staging lane does not read.
"""

import json
import sys
import urllib.request

BASE = "https://services.data.shom.fr/INSPIRE/telechargement/prepackageGroup"
GROUP = "LITTO3D_BZH_2018_2021_PACK_DL"
DOI = "10.17183/LITTO3D_BZH_2018_2021"
# services.data.shom.fr rejects a request carrying no Referer on some of its routes.
HEADERS = {"Accept": "application/json", "Referer": "https://diffusion.shom.fr/"}


def get(url):
    req = urllib.request.Request(url, headers=HEADERS)
    with urllib.request.urlopen(req, timeout=90) as r:
        return json.load(r)


def file_url(prepackage, name):
    return f"{BASE}/{GROUP}/prepackage/{prepackage}/file/{name}"


def harvest():
    packages = [p["prepackageName"] for p in get(f"{BASE}/{GROUP}")["prepackageResources"]]
    urls, total = [], 0
    for i, name in enumerate(sorted(packages), 1):
        for f in get(f"{BASE}/{GROUP}/prepackage/{name}")["downloadFiles"]:
            urls.append(file_url(name, f["fileName"]))
            total += f["fileSize"]
        if i % 50 == 0:
            print(f"  {i}/{len(packages)} prépaquets, {total / 1e9:.1f} GB")
    return urls, total


def write_file_list(urls, total, path):
    header = (
        f"# Litto3D Bretagne 2018-2021 (Shom/IGN, Côtes d'Armor + Ille-et-Vilaine + Morbihan).\n"
        f"# {len(urls)} prépaquets, {total / 1e9:.0f} GB of 7z from the Shom INSPIRE pre-packaged\n"
        f"# download service over anonymous HTTPS. Each holds 1 km² dalles; the build unpacks\n"
        f"# only the 5 m MNT grids (ESRI ASCII, Lambert-93, altitude IGN69, nodata -99999).\n"
        f"# Licence Ouverte / Etalab — cite \"Shom - IGN, 2024. https://doi.org/{DOI}\".\n"
        f"# Generated by harvest.py — re-run it when Shom republishes the prépaquet grid.\n")
    with open(path, "w") as f:
        f.write(header)
        f.writelines(u + "\n" for u in urls)


def _check():
    assert file_url("0225_6770", "0225_6770.7z") == (
        "https://services.data.shom.fr/INSPIRE/telechargement/prepackageGroup/"
        "LITTO3D_BZH_2018_2021_PACK_DL/prepackage/0225_6770/file/0225_6770.7z")
    print("harvest.py self-check ok")


if __name__ == "__main__":
    if sys.argv[1:2] == ["--check"]:
        _check()
    else:
        urls, total = harvest()
        if not urls:
            sys.exit("no prépaquets found — check the group name against GetCapabilities.")
        write_file_list(urls, total, f"{sys.path[0]}/file_list.txt")
        print(f"wrote {len(urls)} URLs ({total / 1e9:.1f} GB) to file_list.txt")
