#!/usr/bin/env python3
"""Regenerate the inland low-water gauge CSVs for dgm_w from PEGELONLINE.

NOT part of the build. The build reads the committed CSVs; this refreshes them. Re-run when the
WSV republishes a low-water datum (a new GlW/Stauziel edition, every several years):

  python harvest_gauges.py            # rewrites every reach CSV in REACHES
  python harvest_gauges.py --check    # offline self-test

Each inland reach's low-water datum is a per-gauge value PEGELONLINE publishes as a characteristic
value, plus the gauge's Pegelnullpunkt (gaugeZero) in NHN — so datum-in-NHN = gaugeZero + value/100,
no PDF tables. build_reference.py turns each CSV into a reference surface subtracted from the NHN bed.

  stations: GET .../stations.json?waters=<WATER>          → km, longitude, latitude, uuid per gauge
  datum:    GET .../stations/<uuid>/W.json?includeCharacteristicValues=true
            → gaugeZero + characteristicValues[]; we read the reach's CHAR (GlW or ZS_I)

Reaches (see the datum problem in README.md):
  - Rhein, free-flowing below the Iffezheim barrage (km 336): GlW (gleichwertiger Wasserstand).
  - Main, impounded to the DEM's extent (km 0–~102): ZS_I (Stauziel, the pool target level).

We keep only gauges (a) in the reach's km window, (b) referenced to NHN — the Swiss upper-Rhein
gauges report gaugeZero in "mü.M." and Dutch ones in NAP, neither NHN — and (c) that publish CHAR.
Stdlib only.
"""

import csv
import json
import os
import sys
import urllib.request

BASE = "https://pegelonline.wsv.de/webservices/rest-api/v2"
NHN_UNIT = "m. ü. NHN"   # gaugeZero unit that marks a gauge as referenced to German NHN

# name: (water, characteristic value, min_km, max_km, output csv). max_km caps the reach a little
# past the DEM's upstream tile so np.interp brackets rather than clamps the last covered pixel.
REACHES = {
    "rhein": ("RHEIN", "GlW", 336.0, 9e9, "rhein_glw.csv"),   # free-flowing below Iffezheim
    "main":  ("MAIN", "ZS_I", 0.0, 125.0, "main_zs.csv"),     # impounded; DEM reaches km ~102
}


def datum_nhn(gauge_zero_m, value_cm):
    """Low-water datum height in NHN: gauge datum (m NHN) + the characteristic value (cm above it)."""
    return round(gauge_zero_m + value_cm / 100.0, 3)


def pick(station, timeseries, char, min_km, max_km):
    """(lon, lat, km, datum_nhn_m) for an in-window NHN gauge that publishes CHAR, else None."""
    km = station.get("km")
    if km is None or not (min_km <= km <= max_km):
        return None
    gz = timeseries.get("gaugeZero") or {}
    if gz.get("unit") != NHN_UNIT or gz.get("value") is None:
        return None
    val = next((c["value"] for c in timeseries.get("characteristicValues", [])
                if c["shortname"] == char), None)
    if val is None:
        return None
    return (station["longitude"], station["latitude"], km, datum_nhn(gz["value"], val))


def _get(url):
    with urllib.request.urlopen(url, timeout=60) as r:
        return json.load(r)


def harvest(water, char, min_km, max_km):
    rows = []
    for s in _get(f"{BASE}/stations.json?waters={water}"):
        try:
            ts = _get(f"{BASE}/stations/{s['uuid']}/W.json?includeCharacteristicValues=true")
        except Exception as ex:
            print(f"  {s.get('shortname')}: fetch failed ({ex})")
            continue
        picked = pick(s, ts, char, min_km, max_km)
        if picked:
            rows.append((s["shortname"], *picked))
    return sorted(rows, key=lambda r: r[3])  # upstream -> downstream by km


def write_csv(rows, char, path):
    header = (
        f"# dgm_w inland low-water reference gauges — {char} in NHN. Generated by harvest_gauges.py\n"
        f"# from PEGELONLINE (https://www.pegelonline.wsv.de/webservices/rest-api/v2/); regenerate when\n"
        f"# the WSV republishes {char}. datum_nhn_m = gaugeZero + {char}/100 (gaugeZero unit 'm. ü. NHN').\n"
        f"# Attribution: © Wasserstraßen- und Schifffahrtsverwaltung des Bundes (WSV) / BfG.\n"
    )
    with open(path, "w", encoding="utf-8", newline="") as f:
        f.write(header)
        w = csv.writer(f)
        w.writerow(["gauge", "lon", "lat", "km", "datum_nhn_m"])
        w.writerows((r[0], r[1], r[2], r[3], r[4]) for r in rows)


def _check():
    # arithmetic: Maxau GlW (gaugeZero 97.721 m NHN, 372 cm) -> 101.441 m NHN
    assert datum_nhn(97.721, 372.0) == 101.441
    ts = {"gaugeZero": {"unit": NHN_UNIT, "value": 97.721},
          "characteristicValues": [{"shortname": "GlW", "value": 372.0}]}
    assert pick({"km": 362.3, "longitude": 8.3, "latitude": 49.0}, ts, "GlW", 336.0, 9e9) \
        == (8.3, 49.0, 362.3, 101.441)
    # dropped: out of window, non-NHN datum, missing the requested characteristic value
    assert pick({"km": 227.6, "longitude": 7.5, "latitude": 48.0}, ts, "GlW", 336.0, 9e9) is None
    assert pick({"km": 500.0, "longitude": 8.0, "latitude": 50.0},
                {**ts, "gaugeZero": {"unit": "mü.M.", "value": 240.0}}, "GlW", 336.0, 9e9) is None
    assert pick({"km": 76.4, "longitude": 9.0, "latitude": 50.0}, ts, "ZS_I", 0.0, 125.0) is None
    print("harvest_gauges.py self-check ok")


def main():
    here = sys.path[0]
    for name, (water, char, min_km, max_km, out) in REACHES.items():
        rows = harvest(water, char, min_km, max_km)
        if not rows:
            sys.exit(f"{name}: no {char} gauges found — the API may have moved; check the site.")
        write_csv(rows, char, os.path.join(here, out))
        print(f"{name}: wrote {len(rows)} gauges to {out} (km {rows[0][3]:.0f}–{rows[-1][3]:.0f})")


if __name__ == "__main__":
    if sys.argv[1:2] == ["--check"]:
        _check()
    else:
        main()
