#!/usr/bin/env python3
"""Regenerate file_list.txt for the NZ Coastal LiDAR source (NOT part of the build).

The build just downloads the URLs in file_list.txt (prepared lane: fetch -> normalize
to a ZSTD COG -> R2). Re-run this when LINZ publishes new coastal surveys (the 3D
Coastal Mapping programme runs through mid-2027, adding surveys incrementally):

  python harvest.py            # walks the public STAC catalog, rewrites file_list.txt

Why a harvest (prepared lane) and not the volatile mirror lane: the collection is small
(~250 MB), so downloading beats streaming a mirror. The bucket IS anonymously listable, but a
flat key listing mixes dem_1m with dsm_1m surface models and coarser dem_2m/10m downsamples;
the STAC catalog names the dem_1m collections directly, so we select the finest bare-earth +
seabed product without regex-filtering keys. Walk: root catalog.json -> per-survey
collection.json -> items. Each item's COG is <item-stem>.tiff beside its <item-stem>.json in the
same collection dir (LINZ's fixed convention); a divergence would surface as a 404 at fetch,
not a silent gap. ~400 tiles, ~250 MB today. Stdlib only, no pipeline coupling.

  index:    GET catalog.json                       (STAC root; child -> collection.json hrefs)
  survey:   GET <survey>/dem_1m/2193/collection.json  (item -> <stem>.json hrefs)
  tile:     GET <survey>/dem_1m/2193/<stem>.tiff       (COG, EPSG:2193, NZVD2016, LERC)
"""

import json
import sys
import urllib.request
from urllib.parse import urljoin

ROOT = "https://nz-coastal.s3.ap-southeast-2.amazonaws.com/catalog.json"


def get_json(url):
    req = urllib.request.Request(url, headers={"User-Agent": "openwaters-harvest"})
    with urllib.request.urlopen(req, timeout=60) as r:
        return json.load(r)


def dem_1m_collections(catalog, base):
    """Absolute collection.json URLs for the dem_1m surveys (skips dsm_1m and coarser dems)."""
    return [urljoin(base, l["href"]) for l in catalog.get("links", [])
            if l.get("rel") == "child" and "/dem_1m/" in l["href"]]


def tile_urls(collection, base):
    """Absolute COG URLs for a collection: each item's <stem>.json href -> <stem>.tiff."""
    return [urljoin(base, l["href"][:-len(".json")] + ".tiff")
            for l in collection.get("links", [])
            if l.get("rel") == "item" and l["href"].endswith(".json")]


def harvest():
    tiles, errors = set(), 0
    collections = dem_1m_collections(get_json(ROOT), ROOT)
    print(f"{len(collections)} dem_1m collections")
    for i, curl in enumerate(collections, 1):
        try:
            tiles.update(tile_urls(get_json(curl), curl))
        except Exception as ex:
            errors += 1
            print(f"  collection {i}/{len(collections)} failed: {ex}")
        if i % 5 == 0:
            print(f"  {i}/{len(collections)} collections, {len(tiles)} tiles")
    if errors:
        print(f"WARNING: {errors} collection(s) failed — coverage may be incomplete; re-run.")
    return sorted(tiles)


def write_file_list(tiles, path):
    header = (
        f"# New Zealand Coastal LiDAR 1m DEM (LINZ) — CC-BY-4.0. {len(tiles)} bare-earth +\n"
        f"# seabed COG tiles (EPSG:2193, NZVD2016, LERC), one per line, harvested from the\n"
        f"# public STAC catalog. Generated by harvest.py — re-run it when LINZ publishes new\n"
        f"# coastal surveys (3D Coastal Mapping programme, through mid-2027).\n")
    with open(path, "w") as f:
        f.write(header)
        f.writelines(t + "\n" for t in tiles)


def _check():
    base = "https://nz-coastal.s3.ap-southeast-2.amazonaws.com/catalog.json"
    cat = {"links": [
        {"rel": "child", "href": "./auckland/x_2025/dem_1m/2193/collection.json"},
        {"rel": "child", "href": "./auckland/x_2025/dem_10m/2193/collection.json"},  # coarser dem
        {"rel": "child", "href": "./auckland/x_2025/dsm_1m/2193/collection.json"},   # surface model
        {"rel": "root", "href": "./catalog.json"}]}
    cols = dem_1m_collections(cat, base)
    assert cols == ["https://nz-coastal.s3.ap-southeast-2.amazonaws.com/"
                    "auckland/x_2025/dem_1m/2193/collection.json"], cols  # dem_1m only
    curl = cols[0]
    coll = {"links": [
        {"rel": "item", "href": "./AY31_10000_0103.json"},
        {"rel": "self", "href": "./collection.json"}]}
    assert tile_urls(coll, curl) == ["https://nz-coastal.s3.ap-southeast-2.amazonaws.com/"
                                     "auckland/x_2025/dem_1m/2193/AY31_10000_0103.tiff"], tile_urls(coll, curl)
    print("harvest.py self-check ok")


if __name__ == "__main__":
    if sys.argv[1:2] == ["--check"]:
        _check()
    else:
        path = f"{sys.path[0]}/file_list.txt"
        tiles = harvest()
        if not tiles:
            sys.exit("no tiles found — the STAC layout may have moved; check catalog.json.")
        write_file_list(tiles, path)
        print(f"wrote {len(tiles)} tile URLs to {path}")
