#!/usr/bin/env python3
"""Regenerate file_list.txt for the Kartverket 50 m sea terrain models (NOT part of the build).

The build just fetches the URLs in file_list.txt — anonymous HTTPS, no API, no login:

  python harvest.py            # reads the TIFF Atom feed, rewrites file_list.txt

Geonorge publishes one Atom feed per distribution format, each listing every D-cell as a
static .zip link. The feed is XML rather than a plain URL list, so it can't drive a
`filter`ed listed enumeration — re-run this when Kartverket surveys more cells (the
dataset's stated maintenance cadence is weekly). Links are matched by regex rather than an
XML parser, which sidesteps entity expansion on a 2 MB remote payload. Stdlib only.
"""

import re
import sys
import urllib.request

FEED = ("https://nedlasting.geonorge.no/geonorge/ATOM-feeds/"
        "SjoTerrengmodellerDTM50_AtomFeedTIFF.xml")
LINK_RE = re.compile(r'<link\s+rel="alternate"\s+href="([^"]+\.zip)"')


def cell_urls(xml):
    return sorted(set(LINK_RE.findall(xml)))


def harvest():
    with urllib.request.urlopen(FEED, timeout=180) as r:
        return cell_urls(r.read().decode("utf-8"))


def write_file_list(urls, path):
    header = (
        f'# Kartverket "Dybdedata - terrengmodeller 50 meters grid" — {len(urls)} NHS D-cells\n'
        "# (0.5 degrees of latitude each), every one a zipped Float32 GeoTIFF in EPSG:25833,\n"
        "# nodata 99999, seafloor negative (elevation, like GEBCO). ~700 MB zipped.\n"
        f"# Static links from the Geonorge TIFF Atom feed ({FEED}),\n"
        "# anonymous HTTPS. Generated by harvest.py — re-run it as Kartverket surveys more cells.\n")
    with open(path, "w") as f:
        f.write(header)
        f.writelines(u + "\n" for u in urls)


def _check():
    entry = (
        '<entry><category term="Celle" label="NHS-D0308"/>\n'
        '<id>https://x/Basisdata_NHS-D0308_Celle_25833_SjoTerrengmodellerDTM50_TIFF.zip_2025</id>\n'
        '<link rel="alternate" href="https://x/b.zip" type="application/gml+xml;version=3.2.1"/>\n'
        '<link rel="alternate" href="https://x/a.zip" type="application/gml+xml"/></entry>')
    # the <id> element carries the same path with a timestamp glued on; only <link href> is a URL
    assert cell_urls(entry) == ["https://x/a.zip", "https://x/b.zip"], cell_urls(entry)
    print("harvest.py self-check ok")


if __name__ == "__main__":
    if sys.argv[1:2] == ["--check"]:
        _check()
    else:
        path = f"{sys.path[0]}/file_list.txt"
        urls = harvest()
        if not urls:
            sys.exit("no cells in the feed — check the Geonorge Atom feed URL.")
        write_file_list(urls, path)
        print(f"wrote {len(urls)} cell URLs to {path}")
